name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install xmlstarlet
      run: sudo apt-get update && sudo apt-get install xmlstarlet

    - name: Install libpcap
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Check test coverage
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml --output-dir=target/coverage.xml

    - name: Check coverage threshold
      run: |
        coverage=$(xmlstarlet sel -t -v "sum(//coverage)" target/coverage.xml)
        threshold=50
        if [ "$coverage" -lt "$threshold" ]; then
          echo "Coverage is below $threshold%. Please increase test coverage before merging."
          exit 1
        fi
